/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerAluno;
import Controller.ControllerCursoAluno;
import Model.Aluno;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * View de Aluno
 * @author guilh
 */
public class AlunoFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlunoFrame
     */
    ControllerAluno ctrlAl;
    ControllerCursoAluno ctrlCa;
    int codigoAluno;
    HomeFrame homeFrame = new HomeFrame();
    public AlunoFrame() {
        this.ctrlCa = new ControllerCursoAluno();
        this.ctrlAl = new ControllerAluno();
        initComponents();
        txtAlterarNome.setVisible(false);
        labelNovoNome.setVisible(false);
        labelNome.setVisible(false);
        btnAlterar.setVisible(false);
        btnExcluir.setVisible(false);
        labelNomeAluno.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltaMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDAluno = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        txtAlterarNome = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        labelNovoNome = new javax.swing.JLabel();
        btnVoltaMenu2 = new javax.swing.JButton();
        labelNomeAluno = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        btnListaAlunos = new javax.swing.JButton();
        btnVoltaMenu3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(710, 408));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltaMenu.setText("Voltar para o menu");
        btnVoltaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltaMenu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(237, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltaMenu)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addGap(231, 231, 231))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setText("Alterar Dados");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Digite o ID do Aluno");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelNome.setText("Nome:");

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        labelNovoNome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelNovoNome.setText("Digite o novo nome");

        btnVoltaMenu2.setText("Voltar para o menu");
        btnVoltaMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaMenu2ActionPerformed(evt);
            }
        });

        labelNomeAluno.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelNomeAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeAluno.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelNovoNome)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVoltaMenu2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(265, 265, 265))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNomeAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltaMenu2)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNomeAluno)
                .addGap(22, 22, 22)
                .addComponent(labelNovoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar Dados", jPanel2);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setText("Listagem de Alunos");

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo do Aluno", "Nome do Aluno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAlunos);

        btnListaAlunos.setText("Listar todos os alunos");
        btnListaAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaAlunosActionPerformed(evt);
            }
        });

        btnVoltaMenu3.setText("Voltar para o menu");
        btnVoltaMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaMenu3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnVoltaMenu3)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 124, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnListaAlunos)
                                .addGap(273, 273, 273))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltaMenu3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListaAlunos)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listagem de Alunos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de click do botão que requisita ao Controller o cadastro de um aluno
     * @param evt 
     */
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(txtNomeAluno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o nome do aluno");
        }
        else{
            String nome = txtNomeAluno.getText();
            boolean inseriu = false;
            try {
                inseriu = ctrlAl.insereAluno(nome);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(inseriu){
                JOptionPane.showMessageDialog(null, "Aluno Cadastrado com sucesso!");
                txtNomeAluno.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "Falha no cadastro");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * Evendo de click do botão para voltar ao menu
     * @param evt 
     */
    private void btnVoltaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaMenuActionPerformed
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaMenuActionPerformed

    /**
     * Evento de click do botão que requisita ao controller a verificação da existencia de um Aluno
     * @param evt 
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ArrayList<Aluno> resultAluno = new ArrayList();
        if(txtIDAluno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o codigo do aluno!");
        }
        else{
            int idAluno = Integer.parseInt(txtIDAluno.getText());
            try {
                resultAluno = ctrlAl.verificaId(idAluno);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(!resultAluno.isEmpty()){
                
                for(Aluno al: resultAluno){
                    labelNomeAluno.setText("Aluno: " + al.getNome());
                }
                
                codigoAluno = idAluno;
                labelNomeAluno.setVisible(true);
                txtAlterarNome.setVisible(true);
                labelNovoNome.setVisible(true);
                labelNome.setVisible(true);
                btnAlterar.setVisible(true);
                btnExcluir.setVisible(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Aluno não encontrado!");
                txtIDAluno.setText("");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Evento de click do botão que requisita a exclusão de um Aluno
     * @param evt 
     */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o aluno?");
        boolean excluiu = false;
        boolean possuiMatriculas = false;
        
        if(resposta == 0){
            try {
                possuiMatriculas = ctrlCa.verificaSeEstaCadastrado(codigoAluno);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(possuiMatriculas){
                resposta = JOptionPane.showConfirmDialog(this, "O aluno está matriculado em um curso e sua matricula irá ser removida. Deseja continuar?");
                if(resposta == 0){
                    try {
                        ctrlCa.excluiuCursoAluno(codigoAluno);
                        excluiu = ctrlAl.excluiuAluno(codigoAluno);
                    } catch (SQLException | ClassNotFoundException ex) {
                        Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    if(excluiu){
                        JOptionPane.showMessageDialog(null, "Aluno excluido com sucesso!");
                        txtAlterarNome.setVisible(false);
                        labelNovoNome.setVisible(false);
                        labelNome.setVisible(false);
                        btnAlterar.setVisible(false);
                        btnExcluir.setVisible(false);
                        txtIDAluno.setText("");
                        labelNomeAluno.setVisible(false);
                    }
                }
                
            }else{
                try {
                    excluiu = ctrlAl.excluiuAluno(codigoAluno);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(excluiu){
                    JOptionPane.showMessageDialog(null, "Aluno excluido com sucesso!");
                    txtAlterarNome.setVisible(false);
                    labelNovoNome.setVisible(false);
                    labelNome.setVisible(false);
                    btnAlterar.setVisible(false);
                    btnExcluir.setVisible(false);
                    txtIDAluno.setText("");
                    labelNomeAluno.setVisible(false);
                }                
            }
                
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    /**
     * Evento de click do botão que requisita ao controller a alteração de dados do Aluno
     * @param evt 
     */
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(txtAlterarNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o novo nome que o aluno irá receber!");
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja alterar o nome do Aluno?");
            if(resposta == 0){
                boolean alterou = false;
                String novoNome = txtAlterarNome.getText();
                try{
                    alterou = ctrlAl.alterarDados(codigoAluno, novoNome);
                }
                catch(SQLException | ClassNotFoundException ex){
                    Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                if(alterou){
                    JOptionPane.showMessageDialog(null, "Nome alterado com sucesso!");
                    txtAlterarNome.setVisible(false);
                    labelNovoNome.setVisible(false);
                    labelNome.setVisible(false);
                    btnAlterar.setVisible(false);
                    btnExcluir.setVisible(false);
                    txtIDAluno.setText("");
                }
            }
            
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * Evento de click do botão que requisita ao controller a listagem dos Alunos
     * @param evt 
     */
    private void btnListaAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAlunosActionPerformed
        ArrayList<Aluno> listaAlunos;
        
        try{
            listaAlunos = ctrlAl.listar();
            DefaultTableModel dados = (DefaultTableModel) tabelaAlunos.getModel();
            dados.setNumRows(0);
            for(Aluno al: listaAlunos){
                dados.addRow(new Object[]{al.getCodigo(), al.getNome()});
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AlunoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListaAlunosActionPerformed
    
    /**
     * Evendo de click do botão para voltar ao menu
     * @param evt 
     */
    private void btnVoltaMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaMenu2ActionPerformed
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaMenu2ActionPerformed
    
    /**
     * Evendo de click do botão para voltar ao menu
     * @param evt 
     */
    private void btnVoltaMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaMenu3ActionPerformed
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListaAlunos;
    private javax.swing.JButton btnVoltaMenu;
    private javax.swing.JButton btnVoltaMenu2;
    private javax.swing.JButton btnVoltaMenu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeAluno;
    private javax.swing.JLabel labelNovoNome;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTextField txtAlterarNome;
    private javax.swing.JTextField txtIDAluno;
    private javax.swing.JTextField txtNomeAluno;
    // End of variables declaration//GEN-END:variables
}
