/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerCurso;
import Controller.ControllerCursoAluno;
import Model.Curso;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * View de Curso
 * @author guilh
 */
public class CursoFrame extends javax.swing.JFrame {

    /**
     * Creates new form Curso
     */
    ControllerCurso ctrlCs = new ControllerCurso();
    ControllerCursoAluno ctrlCa = new ControllerCursoAluno();
    HomeFrame homeFrame = new HomeFrame();
    int codigoCurso;
    public CursoFrame() {
        initComponents();
        labelEmenta.setVisible(false);
        labelDescricao.setVisible(false);
        txtNovaDescricao.setVisible(false);
        txtNovaEmenta.setVisible(false);
        labelEmentaCurso.setVisible(false);
        labelDescricaoCurso.setVisible(false);
        btnAlterar.setVisible(false);
        btnExcluir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmenta = new javax.swing.JTextField();
        btnVoltaMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdCurso = new javax.swing.JTextField();
        btnBuscaId = new javax.swing.JButton();
        labelDescricao = new javax.swing.JLabel();
        labelEmenta = new javax.swing.JLabel();
        txtNovaDescricao = new javax.swing.JTextField();
        txtNovaEmenta = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        labelDescricaoCurso = new javax.swing.JLabel();
        labelEmentaCurso = new javax.swing.JLabel();
        btnVoltaMenu2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCursos = new javax.swing.JTable();
        btnListarCursos = new javax.swing.JButton();
        btnVoltaMenu3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descrição:");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setAutoscrolls(true);

        btnCadastrar.setText("Cadastro");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Ementa:");

        btnVoltaMenu.setText("Voltar para o menu");
        btnVoltaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(txtEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(242, 242, 242))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltaMenu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltaMenu)
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addGap(197, 197, 197))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setText("Alterar Dados");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Digite o ID do curso");

        btnBuscaId.setText("Buscar");
        btnBuscaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaIdActionPerformed(evt);
            }
        });

        labelDescricao.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelDescricao.setText("Descrição");

        labelEmenta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelEmenta.setText("Ementa");

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        labelDescricaoCurso.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelDescricaoCurso.setText("jLabel9");

        labelEmentaCurso.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelEmentaCurso.setText("jLabel9");

        btnVoltaMenu2.setText("Voltar para o menu");
        btnVoltaMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaMenu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 263, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescricao)
                            .addComponent(labelEmenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNovaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNovaEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(247, 247, 247))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnBuscaId)
                            .addGap(330, 330, 330)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdCurso)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltaMenu2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmentaCurso)
                    .addComponent(labelDescricaoCurso))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltaMenu2)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnBuscaId)
                .addGap(19, 19, 19)
                .addComponent(labelDescricaoCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmentaCurso)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao)
                    .addComponent(txtNovaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmenta)
                    .addComponent(txtNovaEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("Alterar de dados", jPanel2);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setText("Listagem");

        tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Ementa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCursos);

        btnListarCursos.setText("Listar todos os cursos");
        btnListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCursosActionPerformed(evt);
            }
        });

        btnVoltaMenu3.setText("Voltar para o menu");
        btnVoltaMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaMenu3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnListarCursos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltaMenu3)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltaMenu3)
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarCursos)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listagem de Cursos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de click do botão que requisita ao Controller o cadastro de um curso
     * @param evt 
     */
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(txtDescricao.getText().isEmpty() || txtEmenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            boolean inseriu = false;
            String descricao = txtDescricao.getText();
            String ementa = txtEmenta.getText();
            
            try {
                inseriu = ctrlCs.insereCurso(descricao, ementa);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(inseriu){
                JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso!");
                txtDescricao.setText("");
                txtEmenta.setText("");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed
    
    /**
     * Evendo de click do botão para voltar ao menu
     * @param evt 
     */
    private void btnVoltaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaMenuActionPerformed
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaMenuActionPerformed

    /**
     * Evento de click do botão que requisita ao controller a listagem dos Cursos
     * @param evt 
     */
    private void btnListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCursosActionPerformed
        ArrayList<Curso> listaCursos;
        
        try{
            listaCursos = ctrlCs.listar();
            DefaultTableModel dados = (DefaultTableModel) tabelaCursos.getModel();
            dados.setNumRows(0);
            for(Curso cs: listaCursos){
                dados.addRow(new Object[]{cs.getCodigo(), cs.getDescricao(), cs.getEmenta()});
            }
        }
        catch(SQLException | ClassNotFoundException ex){
            Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarCursosActionPerformed
    
   
    /**
     * Evendo de click do botão para voltar ao menu
     * @param evt 
     */
    private void btnVoltaMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaMenu3ActionPerformed
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaMenu3ActionPerformed

    /**
     * Evento de click do botão que requisita a exclusão de um Curso
     * @param evt 
     */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o curso?");
        boolean excluiu = false;
        boolean possuiMatriculas = false;
        if(resposta == 0){
            
            try {
                possuiMatriculas = ctrlCa.verificaSeCursoEstaCadastrado(codigoCurso);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(possuiMatriculas){
                resposta = JOptionPane.showConfirmDialog(this, "O curso possui matriculas que serão apagadas. Deseja continuar?");
                
                if(resposta == 0){
                    try {
                        ctrlCa.excluiuCursos(codigoCurso);
                        excluiu = ctrlCs.excluiuCurso(codigoCurso);
                    } catch (SQLException | ClassNotFoundException ex) {
                        Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    if(excluiu){
                        JOptionPane.showMessageDialog(null, "Curso excluido com sucesso!");
                        labelEmenta.setVisible(false);
                        labelDescricao.setVisible(false);
                        txtNovaDescricao.setVisible(false);
                        txtNovaEmenta.setVisible(false);
                        labelEmentaCurso.setVisible(false);
                        labelDescricaoCurso.setVisible(false);
                        btnAlterar.setVisible(false);
                        btnExcluir.setVisible(false);
                        txtIdCurso.setText("");
                    }
                }
            }
            
            try {
                excluiu = ctrlCs.excluiuCurso(codigoCurso);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            if(excluiu){
                JOptionPane.showMessageDialog(null, "Curso excluido com sucesso!");
                labelEmenta.setVisible(false);
                labelDescricao.setVisible(false);
                txtNovaDescricao.setVisible(false);
                txtNovaEmenta.setVisible(false);
                labelEmentaCurso.setVisible(false);
                labelDescricaoCurso.setVisible(false);
                btnAlterar.setVisible(false);
                btnExcluir.setVisible(false);
                txtIdCurso.setText("");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * Evento de click do botão que requisita ao controller a alteração de dados do Curso
     * @param evt 
     */
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(txtNovaDescricao.getText().isEmpty() || txtNovaEmenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite os novos dados do curso!");
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja alterar os dados do Curso?");
            if(resposta == 0){
                boolean alterou = false;
                String novaDescricao = txtNovaDescricao.getText();
                String novaEmenta = txtNovaEmenta.getText();

                try {
                    alterou = ctrlCs.alterarDados(codigoCurso, novaDescricao, novaEmenta);
                } catch (SQLException ex) {
                    Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                //VERIFICAÇÃO DO UPDATE DE CURSO
                if(alterou){
                    //EXIBINDO MENSAGEM PARA O USUARIO
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                    //RESETANDO OS VALORES E TIRANDO A VISIBILIDADE DE ALGUNS COMPONENTES
                    labelEmenta.setVisible(false);
                    labelDescricao.setVisible(false);
                    txtNovaDescricao.setVisible(false);
                    txtNovaEmenta.setVisible(false);
                    labelEmentaCurso.setVisible(false);
                    labelDescricaoCurso.setVisible(false);
                    btnAlterar.setVisible(false);
                    btnExcluir.setVisible(false);
                    txtIdCurso.setText("");
                    txtNovaDescricao.setText("");
                    txtNovaEmenta.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * Evento de click do botão que requisita ao controller a verificação da existencia de um Curso
     * @param evt 
     */
    private void btnBuscaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaIdActionPerformed
        ArrayList<Curso> resultCurso = new ArrayList();

        if(txtIdCurso.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o codigo do curso!");
        }
        else{
            int idCurso = Integer.parseInt(txtIdCurso.getText());
            try {
                resultCurso = ctrlCs.verificaId(idCurso);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CursoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            if(!resultCurso.isEmpty()){
                for(Curso cs: resultCurso){
                    labelDescricaoCurso.setText("Descricao: " + cs.getDescricao());
                    labelEmentaCurso.setText("Ementa: " + cs.getEmenta());
                }
                codigoCurso = idCurso;
                labelEmenta.setVisible(true);
                labelDescricao.setVisible(true);
                txtNovaDescricao.setVisible(true);
                txtNovaEmenta.setVisible(true);
                labelEmentaCurso.setVisible(true);
                labelDescricaoCurso.setVisible(true);
                btnAlterar.setVisible(true);
                btnExcluir.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Curso não encontrado!");
                txtIdCurso.setText("");
            }
        }
    }//GEN-LAST:event_btnBuscaIdActionPerformed

    private void btnVoltaMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaMenu2ActionPerformed
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscaId;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListarCursos;
    private javax.swing.JButton btnVoltaMenu;
    private javax.swing.JButton btnVoltaMenu2;
    private javax.swing.JButton btnVoltaMenu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelDescricaoCurso;
    private javax.swing.JLabel labelEmenta;
    private javax.swing.JLabel labelEmentaCurso;
    private javax.swing.JTable tabelaCursos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEmenta;
    private javax.swing.JTextField txtIdCurso;
    private javax.swing.JTextField txtNovaDescricao;
    private javax.swing.JTextField txtNovaEmenta;
    // End of variables declaration//GEN-END:variables
}
